package com.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Map;

import com.model.Bill;
import com.model.Product;
import com.util.DatabaseConnection;

public class DatabaseDao {
	
	//Update database table product when new bill generated by Cashier

	public static void updateDatabase(Map<Integer, Bill> cart) {
		String sql = "update product set quantity = ? where id = ?";
		try (Connection con = DatabaseConnection.createConnection();
				PreparedStatement pst = con.prepareStatement(sql);) {
			con.setAutoCommit(false);
			for (Bill item : cart.values()) {
				Product p = item.getProduct();
				int newQty = p.getQuantity() - item.getquantity();
				pst.setInt(1, newQty);
				pst.setInt(2, p.getId());
				pst.executeUpdate(); 

			}
			con.commit();
		} catch (SQLException e) {
			e.printStackTrace();
		}

	}
	
}
