package com.dao;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import com.model.Bill;
import com.model.Product;
import com.util.DatabaseConnection;




public class DatabaseDao {
	
	//auto update
	//Update database table product when new bill generated by Cashier

	public static void updateDatabase(Map<Integer, Bill> cart) {
		String sql = "update product set quantity = ? where id = ?";
		try (Connection con = DatabaseConnection.createConnection();
				PreparedStatement pst = con.prepareStatement(sql);) {
			con.setAutoCommit(false);
			for (Bill item : cart.values()) {
				Product p = item.getProduct();
				int newQty = p.getQuantity() - item.getquantity();
				pst.setInt(1, newQty);
				pst.setInt(2, p.getId());
				pst.executeUpdate(); 

			}
			con.commit();
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
 	
	//Add new item 
	public  int addNewProduct(Product p) {
		int check = 0;
		String addNewSql = "insert into product (name,category,price,quantity,discountType,discount) values(?,?,?,?,?,?)";
		try(Connection con = DatabaseConnection.createConnection();
				PreparedStatement pst = con.prepareStatement(addNewSql);){
			pst.setString(1, p.getName());
			pst.setString(2, p.getCategory());
			pst.setDouble(3, p.getPrice());
			pst.setInt(4, p.getQuantity());
			pst.setString(5, p.getDiscountType());
			pst.setDouble(6, p.getDiscount());
			check = pst.executeUpdate();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
		return check;
	}
	//update product 
	public  int updateProductQuantity(Product p) {
		int check = 0;
		String updateSql = "update product set quantity = ? where id = ?";
		try(Connection con = DatabaseConnection.createConnection();
				PreparedStatement pst = con.prepareStatement(updateSql);){
			pst.setInt(1, p.getQuantity());
			pst.setInt(2, p.getId());
			check = pst.executeUpdate();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
		return check ;
	}
	//add new quantity in exiting quantity of product 
	public  int addProductQuantity(Product p) {
		int check = 0;
		String updateSql = "update product set quantity = ? where id = ?";
		try(Connection con = DatabaseConnection.createConnection();
				PreparedStatement pst = con.prepareStatement(updateSql);){
			pst.setInt(1, p.getQuantity());
			pst.setInt(2, p.getId());
			check = pst.executeUpdate();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
		return check ;
	}
	
	//fetch product by id
	public  Product findProductByiId(int id){
 		Product p = null;
 		String sql = "select * from product where id = ?";
 		try(Connection con = DatabaseConnection.createConnection();
 				PreparedStatement prt = con.prepareStatement(sql);){
 			prt.setInt(1, id);
 			ResultSet rs = prt.executeQuery();
 			List<Product> list = DatabaseConnection.productRowMapper(rs);
 			if( ! list.isEmpty()) {
 				p = list.get(0);
 			}
 			
 		}catch (SQLException e) {
 			e.printStackTrace();
 		}
 		return p;
 	}
	
	//delete product
	public int deleteProduct(int id) {
		int check = 0;
		
		String deleteSql = "delete from product where id = ?";
		try(Connection con = DatabaseConnection.createConnection();
				PreparedStatement pst = con.prepareStatement(deleteSql);){
			pst.setInt(1,id);
			check = pst.executeUpdate();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return check ;
	}
	
	//daily revenue
	public  int dailyRevenue(String date) {
		int revenue =  0;
		String revenueSql = "SELECT SUM(final_amount) FROM bills WHERE DATE(bill_date)=?";
		try(Connection con = DatabaseConnection.createConnection();
				PreparedStatement pst = con.prepareStatement(revenueSql);){
			pst.setString(1, date);
			ResultSet rs =pst.executeQuery();
			if(rs.next()) {
				revenue = rs.getInt(1);
			}
			rs.close();
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return revenue;
		
	}
	
	//monthly revenue
	public  int monthlyRevenue(int month , int year) {
		int revenue =  0;
		String revenueSql = "SELECT SUM(final_amount) FROM bills WHERE MONTH(bill_date)=? AND YEAR(bill_date)=?";
		try(Connection con = DatabaseConnection.createConnection();
				PreparedStatement pst = con.prepareStatement(revenueSql);){
			pst.setInt(1, month);
			pst.setInt(2, year);
			ResultSet rs =pst.executeQuery();
			if(rs.next()) {
				revenue = rs.getInt(1);
			}
			rs.close();
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return revenue;
		
	}
	
	//yearly revenue
	public  int yearlyRevenue( int year) {
		int revenue =  0;
		String revenueSql = "SELECT SUM(final_amount) FROM bills WHERE  YEAR(bill_date)=?";
		try(Connection con = DatabaseConnection.createConnection();
				PreparedStatement pst = con.prepareStatement(revenueSql);){
			pst.setInt(1, year);
			ResultSet rs =pst.executeQuery();
			if(rs.next()) {
				revenue = rs.getInt(1);
			}
			rs.close();
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return revenue;
		
	}
	//stack less than given quantity 
	public List<Product> lowStock(int quantity) {
		List<Product> plist = new ArrayList<>();
		String sql = "select * from product where quantity < ? order by quantity desc";
		try(Connection con = DatabaseConnection.createConnection();
				PreparedStatement pst = con.prepareStatement(sql);){
			pst.setInt(1, quantity);
			ResultSet rs = pst.executeQuery();
			if(rs.next()) {
				plist.addAll(DatabaseConnection.productRowMapper(rs) );
			}
			
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return plist;
	}
	public List<Product> displayAllProducts(){
		List<Product> plist = new ArrayList<>();
		String sql = "select * from product";
		try(Connection con = DatabaseConnection.createConnection();
				PreparedStatement pst = con.prepareStatement(sql);){
			ResultSet rs = pst.executeQuery();
			if(rs.next()) {
				plist.addAll(DatabaseConnection.productRowMapper(rs));
			}
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return plist;
	}
}
